pipeline {
  agent {
    kubernetes {
      defaultContainer 'jnlp'
      yamlFile 'doc/kubernetesPod.yaml'
    }
  }

  stages {
    stage('Build && SonarQube analysis') {
        steps{
            container('maven') {
				withSonarQubeEnv(credentialsId: 'sonar', installationName: 'sonar') {
				  sh 'mvn -DskipTests=true clean compile sonar:sonar'
				}
                sh 'mvn -DskipTests=true clean package'
            }
        }
    }
	stage("Quality Gate") {
		steps {
			timeout(time: 1, unit: 'HOURS') {
				// Parameter indicates whether to set pipeline to UNSTABLE if Quality Gate fails
				// true = set pipeline to UNSTABLE, false = don't
				waitForQualityGate abortPipeline: true
			}
		}
	}
    stage('Build Docker Image'){
        steps{
            container('docker'){
                sh '''
                    mkdir context
                    cp target/tlhhup-1.0-SNAPSHOT.jar context
                    cp doc/Dockerfile context
                '''
                sh 'docker build -t harbor.tlh.com/tlhhup/jks:${BUILD_NUMBER} context'
            }
        }
    }
    stage('Push Docker Image'){
        steps{
            container('docker'){
                sh 'echo Push Docker Image'
                withCredentials([usernamePassword(credentialsId: 'harbor', passwordVariable: 'dockerHubPassword', usernameVariable: 'dockerHubUser')]) {
                    sh '''
                        docker login harbor.tlh.com -u ${dockerHubUser} -p ${dockerHubPassword}
                        docker push harbor.tlh.com/tlhhup/jks:${BUILD_NUMBER}
                    '''
                }
            }
        }
    }
    stage('Deploy'){
        steps{
            input "Does the staging environment look ok?"
            container('kubectl'){
                sh 'echo Deploy'
                sh '''
                    mkdir deploy
                    cp doc/deployment.yaml deploy
                '''
                sh "sed -i 's/<BUILD_NUMBER>/${BUILD_NUMBER}/' deploy/deployment.yaml"
                sh 'kubectl apply -f deploy/deployment.yaml -n tlh'
            }
        }
    }
  }
}