apiVersion: "v1"
kind: "Pod"
metadata:
  labels:
    jenkins: "slave"
spec:
  containers:
    - name: "maven"
      image: "maven:3.5-jdk-8"
      imagePullPolicy: "IfNotPresent"
      resources:
        limits: {}
        requests: {}
      securityContext:
        privileged: false
      tty: true
      volumeMounts:
        - mountPath: "/root/.m2"
          name: "volume-0"
          readOnly: false
        - mountPath: "/home/jenkins/agent"
          name: "workspace-volume"
          readOnly: false
      command:
        - "cat"
    - name: "kubectl"
      image: "lachlanevenson/k8s-kubectl:latest"
      imagePullPolicy: "IfNotPresent"
      resources:
        limits: {}
        requests: {}
      securityContext:
        privileged: true
      tty: true
      volumeMounts:
        - mountPath: "/home/jenkins/agent"
          name: "workspace-volume"
          readOnly: false
      command:
        - "cat"
    - name: "docker"
      image: "docker:latest"
      imagePullPolicy: "IfNotPresent"
      resources:
        limits: {}
        requests: {}
      securityContext:
        privileged: false
      tty: true
      volumeMounts:
        - mountPath: "/var/run/docker.sock"
          name: "volume-1"
          readOnly: false
        - mountPath: "/home/jenkins/agent"
          name: "workspace-volume"
          readOnly: false
    - name: "jnlp"
      image: "jenkins/jnlp-slave:alpine"
      volumeMounts:
        - mountPath: "/home/jenkins/agent"
          name: "workspace-volume"
          readOnly: false
  nodeSelector: {}
  restartPolicy: "Never"
  serviceAccount: "jenkins"
  volumes:
    - name: "volume-0"
      persistentVolumeClaim:
        claimName: opspvc
    - hostPath:
        path: "/var/run/docker.sock"
      name: "volume-1"
    - emptyDir: {}
      name: "workspace-volume"