dependencies:
  - name: postgresql
    version: 7.7.2
    repository: https://kubernetes-charts.storage.googleapis.com/
    condition: postgresql.enabled
  - name: mysql
    version: 1.4.0
    repository: https://kubernetes-charts.storage.googleapis.com/
    condition: mysql.enabled
